In [1]:
import torch

In [14]:

C = torch.randn((27, 2))   # 形状 [27, 2]
X = torch.tensor([[0, 1, 2],
                  [3, 4, 5]])

Y = C[X]                   # 问题的核心


In [5]:
C

tensor([[ 1.7229,  1.1623],
        [-0.2811,  0.4724],
        [-1.5925, -0.4540],
        [ 0.8360, -0.0303],
        [ 3.5172, -0.1093],
        [-1.1626,  1.1527],
        [-0.1892, -1.5313],
        [ 2.3344, -0.6605],
        [ 0.3138,  0.1057],
        [ 0.2916,  1.1527],
        [ 2.2592, -0.5524],
        [ 0.2156, -0.8751],
        [ 0.0073,  1.2154],
        [ 1.1304, -0.6504],
        [-1.0740, -0.1607],
        [ 0.1354, -0.1082],
        [ 0.6608, -0.9805],
        [-1.4046,  1.7515],
        [-1.7278, -2.7727],
        [ 1.9631,  0.7612],
        [-0.1070,  0.1592],
        [-1.4153, -0.2194],
        [ 0.2779, -1.1253],
        [ 0.5158,  0.5184],
        [-1.7501,  0.2225],
        [-0.2218,  0.0555],
        [ 1.0367,  1.5249]])

In [3]:
X

tensor([[0, 1, 2],
        [3, 4, 5]])

In [4]:
Y

tensor([[[ 1.7229,  1.1623],
         [-0.2811,  0.4724],
         [-1.5925, -0.4540]],

        [[ 0.8360, -0.0303],
         [ 3.5172, -0.1093],
         [-1.1626,  1.1527]]])

In [8]:
X[1, 1]

tensor(4)

In [9]:
C[X][1, 1]

tensor([ 3.5172, -0.1093])

In [ ]:
# build the vocabulary of characters and mappings to/from integers
chars = sorted(list(set(''.join(words))))
stoi = {s:i+1 for i,s in enumerate(chars)}
stoi['.'] = 0
itos = {i:s for s,i in stoi.items()}
print(itos)

In [10]:
C[4]

tensor([ 3.5172, -0.1093])

In [11]:
C[X[1, 1]]

tensor([ 3.5172, -0.1093])

In [17]:
C = torch.randn((27, 2))
X = torch.randn((32, 3), dtype=int)

NotImplementedError: "normal_kernel_cpu" not implemented for 'Long'

In [74]:
# read in all the words
words = open('data/names.txt', 'r').read().splitlines()
words[:8]

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia']

In [28]:
# build the dataset
# 用前三个预测下一个字符
block_size = 3 # context length: how many characters do we take to predict the next one?
X, Y = [], []
for w in words:
  
  #print(w)
  context = [0] * block_size
  for ch in w + '.':
    ix = stoi[ch]
    X.append(context)
    Y.append(ix)
    #print(''.join(itos[i] for i in context), '--->', itos[ix])
    context = context[1:] + [ix] # crop and append
  
X_hat = torch.tensor(X[:32])
Y = torch.tensor(Y)

In [30]:
emb = C[X_hat]
emb.shape

torch.Size([32, 3, 2])

In [32]:
import torch.nn.functional as F

In [33]:
F.one_hot(torch.tensor(5), num_classes=27).shape, C.shape

(torch.Size([27]), torch.Size([27, 2]))

In [34]:
F.one_hot(torch.tensor(5), num_classes=27).float() @ C


tensor([-0.7867,  1.6594])

In [35]:
W1 = torch.randn((6, 100))
b1 = torch.randn(100)

In [37]:
emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]

(tensor([[ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [-0.7867,  1.6594],
         [-0.6899, -2.6921],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [-1.1801, -0.1231],
         [-3.4855, -0.2580],
         [-0.7431,  1.8755],
         [-1.0747,  0.3682],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.2183,  0.5439],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [-0.7431,  1.8755],
         [ 0.2381, -1.6071],
         [ 0.2183,  0.5439],
         [ 1.0368, -1.0921],
         [-0.7867,  1.6594],
         [-3.4855, -0.2580],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [ 0.2381, -1.6071],
         [-1.1801, -0.1231],
         [ 1.2172, -0.5733],
         [ 0.5785,  0.0120]]),
 tensor([[ 0.7816, -0.6910],
         [ 0.7816, -0.6910],
         [-0

In [39]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]]).shape

torch.Size([96, 2])

In [40]:
torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1).shape

torch.Size([32, 6])

In [41]:
emb_update = torch.cat([emb[:, 0, :], emb[:, 1, :], emb[:, 2, :]], 1)

In [42]:
emb_update @ W1 + b1

tensor([[-3.4221, -4.0477, -4.3562,  ..., -2.6597, -0.4938, -2.2848],
        [ 0.5022,  1.7120, -1.7554,  ..., -0.2904,  1.5057, -0.7614],
        [-1.1815, -2.2726, -3.7528,  ..., -0.3477,  3.6135, -3.2374],
        ...,
        [-3.4768, -6.2050,  1.2300,  ...,  1.1881,  1.5280, -1.4609],
        [ 1.6885,  2.0050, -1.6102,  ..., -0.4106,  1.7406, -1.4969],
        [ 1.1064, -4.0104,  1.1602,  ...,  2.2070,  1.8790, -3.3571]])

In [43]:
a = torch.arange(18)
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [44]:
a.view(3, 3 , 2)

tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]])

In [45]:
a.storage()

C:\Users\gofor\AppData\Local\Temp\ipykernel_25388\214256462.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  a.storage()


 0
 1
 2
 3
 4
 5
 6
 7
 8
 9
 10
 11
 12
 13
 14
 15
 16
 17
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 18]

In [46]:
emb.shape

torch.Size([32, 3, 2])

In [47]:
emb.view(32, 6 ) == torch.cat(torch.unbind(emb, 1), 1)

tensor([[True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, True, True],
        [True, True, True, True, T

In [48]:
h = emb.view(32, 6) @ W1 + b1
h.shape

torch.Size([32, 100])

In [49]:
h

tensor([[-3.4221, -4.0477, -4.3562,  ..., -2.6597, -0.4938, -2.2848],
        [ 0.5022,  1.7120, -1.7554,  ..., -0.2904,  1.5057, -0.7614],
        [-1.1815, -2.2726, -3.7528,  ..., -0.3477,  3.6135, -3.2374],
        ...,
        [-3.4768, -6.2050,  1.2300,  ...,  1.1881,  1.5280, -1.4609],
        [ 1.6885,  2.0050, -1.6102,  ..., -0.4106,  1.7406, -1.4969],
        [ 1.1064, -4.0104,  1.1602,  ...,  2.2070,  1.8790, -3.3571]])

In [50]:
h = torch.tanh(h)
h

tensor([[-0.9979, -0.9994, -0.9997,  ..., -0.9903, -0.4572, -0.9795],
        [ 0.4639,  0.9369, -0.9420,  ..., -0.2825,  0.9062, -0.6419],
        [-0.8279, -0.9790, -0.9989,  ..., -0.3343,  0.9985, -0.9969],
        ...,
        [-0.9981, -1.0000,  0.8426,  ...,  0.8300,  0.9101, -0.8978],
        [ 0.9340,  0.9644, -0.9232,  ..., -0.3890,  0.9403, -0.9046],
        [ 0.8028, -0.9993,  0.8211,  ...,  0.9761,  0.9544, -0.9976]])

In [51]:
h.shape

torch.Size([32, 100])

In [52]:
W2 = torch.randn((100, 27))
b2 = torch.randn(27)

In [53]:
logits = h @ W2 + b2

In [54]:
logits.shape

torch.Size([32, 27])

In [55]:
counts = logits.exp()

In [56]:
prob = counts / counts.sum(1, keepdims = True)

In [57]:
prob.shape

torch.Size([32, 27])

In [58]:
prob[0].sum()

tensor(1.0000)

In [61]:
Y_hat = Y[:32]

In [ ]:
# X 是 [32, 3] 3代表的是blocksize=3 也就是3个字符作为上下文， 32是选的前32个单词作为输入


In [ ]:
prob[torch.arange(32), Y_hat] #Y_hat是本该输出的那个字母的index（list）， 32个上下文，取出每一个对应Y_hat的位置的概率，这个概率越大说明预测结果越准确

In [63]:
loss = -prob[torch.arange(32), Y_hat].log().mean()

In [65]:
# --------------- now made respectable :) ----------------
X_hat.shape, Y_hat.shape  # dataset

(torch.Size([32, 3]), torch.Size([32]))

In [66]:
g = torch.Generator().manual_seed(2147483647)  # for reproducibility
C  = torch.randn((27, 2), generator=g)
W1 = torch.randn((6, 100), generator=g)
b1 = torch.randn(100, generator=g)
W2 = torch.randn((100, 27), generator=g)
b2 = torch.randn(27, generator=g)
parameters = [C, W1, b1, W2, b2]

In [67]:
sum(p.nelement() for p in parameters)  # number of parameters in total
# 3481

3481

In [68]:
emb = C[X]                     # (32, 3, 2)
h   = torch.tanh(emb.view(-1, 6) @ W1 + b1)   # (32, 100)
logits = h @ W2 + b2           # (32, 27)
counts = logits.exp()
prob = counts / counts.sum(1, keepdims=True)
loss = -prob[torch.arange(32), Y_hat].log().mean()
loss
# tensor(17.7692)

tensor(17.7697)

In [ ]:
F.cross_entropy(logits, Y_hat)

In [69]:
for p in parameters:
    p.requires_grad = True

In [73]:
for _ in range(10):
    emb = C[X_hat]
    h = torch.tanh(emb.view(-1, 6) @ W1 + b1)
    logits = h @ W2 + b2
    loss = F.cross_entropy(logits, Y_hat)
    print(loss.item())
    for p in parameters:
        p.grad = None
    loss.backward()
    for p in parameters:
        p.data += -0.1 * p.grad

3.985849142074585
3.6028308868408203
3.262141704559326
2.961380958557129
2.6982972621917725
2.469712972640991
2.271660327911377
2.1012840270996094
1.9571772813796997
1.8374855518341064
